#include "GENERAL_CONSTANTS.hpp"
#include "TILE_INFO.hpp"

constexpr Type BOARD_LAYOUT[BOARD_WIDTH][BOARD_HEIGHT] = {
    {TRIPL_WORD, BOARD_TILE, BOARD_TILE, DOUBL_LETR, BOARD_TILE, BOARD_TILE, BOARD_TILE, TRIPL_WORD, BOARD_TILE, BOARD_TILE, BOARD_TILE, DOUBL_LETR, BOARD_TILE, BOARD_TILE, TRIPL_WORD},
    
    {BOARD_TILE, DOUBL_WORD, BOARD_TILE, BOARD_TILE, BOARD_TILE, TRIPL_LETR, BOARD_TILE, BOARD_TILE, BOARD_TILE, TRIPL_LETR, BOARD_TILE, BOARD_TILE, BOARD_TILE, DOUBL_WORD, BOARD_TILE},
    
    {BOARD_TILE, BOARD_TILE, DOUBL_WORD, BOARD_TILE, BOARD_TILE, BOARD_TILE, DOUBL_LETR, BOARD_TILE, DOUBL_LETR, BOARD_TILE, BOARD_TILE, BOARD_TILE, DOUBL_WORD, BOARD_TILE, BOARD_TILE},
    
    {DOUBL_LETR, BOARD_TILE, BOARD_TILE, DOUBL_WORD, BOARD_TILE, BOARD_TILE, BOARD_TILE, DOUBL_LETR, BOARD_TILE, BOARD_TILE, BOARD_TILE, DOUBL_WORD, BOARD_TILE, BOARD_TILE, DOUBL_LETR},
    
    {BOARD_TILE, BOARD_TILE, BOARD_TILE, BOARD_TILE, DOUBL_WORD, BOARD_TILE, BOARD_TILE, BOARD_TILE, BOARD_TILE, BOARD_TILE, DOUBL_WORD, BOARD_TILE, BOARD_TILE, BOARD_TILE, BOARD_TILE},
    
    {BOARD_TILE, TRIPL_LETR, BOARD_TILE, BOARD_TILE, BOARD_TILE, TRIPL_LETR, BOARD_TILE, BOARD_TILE, BOARD_TILE, TRIPL_LETR, BOARD_TILE, BOARD_TILE, BOARD_TILE, TRIPL_LETR, BOARD_TILE},
    
    {BOARD_TILE, BOARD_TILE, DOUBL_LETR, BOARD_TILE, BOARD_TILE, BOARD_TILE, DOUBL_LETR, BOARD_TILE, DOUBL_LETR, BOARD_TILE, BOARD_TILE, BOARD_TILE, DOUBL_LETR, BOARD_TILE, BOARD_TILE},
    
    {TRIPL_WORD, BOARD_TILE, BOARD_TILE, DOUBL_LETR, BOARD_TILE, BOARD_TILE, BOARD_TILE, START_TILE, BOARD_TILE, BOARD_TILE, BOARD_TILE, DOUBL_LETR, BOARD_TILE, BOARD_TILE, TRIPL_WORD},
    
    {BOARD_TILE, BOARD_TILE, DOUBL_LETR, BOARD_TILE, BOARD_TILE, BOARD_TILE, DOUBL_LETR, BOARD_TILE, DOUBL_LETR, BOARD_TILE, BOARD_TILE, BOARD_TILE, DOUBL_LETR, BOARD_TILE, BOARD_TILE},
    
    {BOARD_TILE, TRIPL_LETR, BOARD_TILE, BOARD_TILE, BOARD_TILE, TRIPL_LETR, BOARD_TILE, BOARD_TILE, BOARD_TILE, TRIPL_LETR, BOARD_TILE, BOARD_TILE, BOARD_TILE, TRIPL_LETR, BOARD_TILE},
    
    {BOARD_TILE, BOARD_TILE, BOARD_TILE, BOARD_TILE, DOUBL_WORD, BOARD_TILE, BOARD_TILE, BOARD_TILE, BOARD_TILE, BOARD_TILE, DOUBL_WORD, BOARD_TILE, BOARD_TILE, BOARD_TILE, BOARD_TILE},
    
    {DOUBL_LETR, BOARD_TILE, BOARD_TILE, DOUBL_WORD, BOARD_TILE, BOARD_TILE, BOARD_TILE, DOUBL_LETR, BOARD_TILE, BOARD_TILE, BOARD_TILE, DOUBL_WORD, BOARD_TILE, BOARD_TILE, DOUBL_LETR},
    
    {BOARD_TILE, BOARD_TILE, DOUBL_WORD, BOARD_TILE, BOARD_TILE, BOARD_TILE, DOUBL_LETR, BOARD_TILE, DOUBL_LETR, BOARD_TILE, BOARD_TILE, BOARD_TILE, DOUBL_WORD, BOARD_TILE, BOARD_TILE},
    
    {BOARD_TILE, DOUBL_WORD, BOARD_TILE, BOARD_TILE, BOARD_TILE, TRIPL_LETR, BOARD_TILE, BOARD_TILE, BOARD_TILE, TRIPL_LETR, BOARD_TILE, BOARD_TILE, BOARD_TILE, DOUBL_WORD, BOARD_TILE},
    
    {TRIPL_WORD, BOARD_TILE, BOARD_TILE, DOUBL_LETR, BOARD_TILE, BOARD_TILE, BOARD_TILE, TRIPL_WORD, BOARD_TILE, BOARD_TILE, BOARD_TILE, DOUBL_LETR, BOARD_TILE, BOARD_TILE, TRIPL_WORD}
};