#pragma once
#include "raylib.h"

const int AMOUNT_OF_PLAYERS = 3;
const int PLAYER_HAND_SIZE = 7;
const int WORD_LETTER_REQUIREMENT = 2;

const int BOARD_WIDTH = 15;
const int BOARD_HEIGHT = 15;
const int TILE_SIZE = 32;
const int TILE_GAP = 4;

const int OUTLINE_THICKNESS = 2;

extern Font UI_FONT;
const int UI_FONT_SIZE = 18;
const int UI_FONT_SPACING = 2;
const int UI_OFFSET_VALUE = 32;
const int UI_OUTLINE_THICKNESS = 4;

const float BOARD_START_X = UI_OFFSET_VALUE;
const float BOARD_START_Y = UI_OFFSET_VALUE;
const float BOARD_WIDTH_PIXELS = (BOARD_WIDTH * (TILE_SIZE + TILE_GAP)) - TILE_GAP;
const float BOARD_HEIGHT_PIXELS = (BOARD_HEIGHT * (TILE_SIZE + TILE_GAP)) - TILE_GAP;
const float BOARD_END_X = BOARD_START_X + BOARD_WIDTH_PIXELS;
const float BOARD_END_Y = BOARD_START_Y + BOARD_HEIGHT_PIXELS;

const float BALLOT_WIDTH = BOARD_WIDTH_PIXELS;
const float BALLOT_HEIGHT = BOARD_HEIGHT_PIXELS;
const float BALLOT_END_X = BOARD_END_X;
const float BALLOT_END_Y = BOARD_END_Y;
const float BALLOT_START_X = UI_OFFSET_VALUE;
const float BALLOT_START_Y = UI_OFFSET_VALUE;
const float BALLOT_YESNO_WIDTH = 128;
const float BALLOT_YESNO_HEIGHT = 64;
const float BALLOT_NO_X = BALLOT_END_X - BALLOT_YESNO_WIDTH - UI_OFFSET_VALUE;
const float BALLOT_NO_Y = BALLOT_END_Y - BALLOT_YESNO_HEIGHT - UI_OFFSET_VALUE;
const float BALLOT_YES_X = BALLOT_START_X + UI_OFFSET_VALUE;
const float BALLOT_YES_Y = BALLOT_END_Y - BALLOT_YESNO_HEIGHT - UI_OFFSET_VALUE;

const float GAMEOVER_LEADERBOARD_WIDTH = 128;
const float GAMEOVER_LEADERBOARD_HEIGHT = 512;
const float GAMEOVER_LEADERBOARD_X = BOARD_END_X + UI_OFFSET_VALUE;
const float GAMEOVER_LEADERBOARD_Y = UI_OFFSET_VALUE;

const float PLAY_BUTTON_WIDTH = 128;
const float PLAY_BUTTON_HEIGHT = 64;
const float PLAY_BUTTON_X = BOARD_END_X + UI_OFFSET_VALUE;
const float PLAY_BUTTON_Y = UI_OFFSET_VALUE;

const float WORD_DISPLAY_WIDTH = 128;
const float WORD_DISPLAY_HEIGHT = 256;
const float WORD_DISPLAY_X = PLAY_BUTTON_X;
const float WORD_DISPLAY_Y = PLAY_BUTTON_Y + PLAY_BUTTON_HEIGHT + UI_OFFSET_VALUE;

const float LEADERBOARD_WIDTH = 128;
const float LEADERBOARD_HEIGHT = 128;
const float LEADERBOARD_X = WORD_DISPLAY_X;
const float LEADERBOARD_Y = WORD_DISPLAY_Y + WORD_DISPLAY_HEIGHT + UI_OFFSET_VALUE;

const float WARNING_BOX_WIDTH = 128;
const float WARNING_BOX_HEIGHT = 64;
const float WARNING_BOX_X = LEADERBOARD_X;
const float WARNING_BOX_Y = LEADERBOARD_Y + LEADERBOARD_HEIGHT + UI_OFFSET_VALUE;

// Null_position is used for screen position
const int NULL_POSITION = -100;
// Null_index is used for tile index information
const int NULL_INDEX = -1;

const int TILE_FONT_SIZE = 18;
const int TILE_FONT_SPACING = 2;

const float HAND_DISPLAY_LENGTH = PLAYER_HAND_SIZE * (TILE_SIZE + TILE_GAP) - TILE_GAP;
const float HAND_DISPLAY_HEIGHT = TILE_SIZE;
// Centered under board
const float HAND_START_X = BOARD_START_X + ((BOARD_WIDTH * (TILE_SIZE + TILE_GAP)) - HAND_DISPLAY_LENGTH) / 2;
const float HAND_START_Y = BOARD_END_X + UI_OFFSET_VALUE;

enum WarningType {
    SELECT_MYSTERY_TILE,
    LAST_TURN,
    TILES_LEFT_REMINDER
};

extern Font TILE_FONT;