#pragma once
#include "GENERAL_CONSTANTS.hpp"

const int WINDOW_WIDTH = UI_OFFSET_VALUE + BOARD_WIDTH_PIXELS + UI_OFFSET_VALUE + PLAY_BUTTON_WIDTH + UI_OFFSET_VALUE;
const int WINDOW_HEIGHT = UI_OFFSET_VALUE + BOARD_HEIGHT_PIXELS + UI_OFFSET_VALUE + HAND_DISPLAY_HEIGHT + UI_OFFSET_VALUE;

